- name: "install rustup"
  ansible.builtin.shell:
    cmd: curl https://sh.rustup.rs -sSf | CARGO_HOME={{ ansible_user_dir }}/.local/share/cargo RUSTUP_HOME={{ansible_user_dir }}/.local/share/rustup sh -s -- -y --no-modify-path
    creates: "{{ ansible_user_dir }}/.local/share/rustup"
  register: install

- name: "bashrc rust"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/bash/100.rust.sh"
    content: |
      export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
      export CARGO_HOME="$XDG_DATA_HOME/cargo"
      . "$CARGO_HOME/env"
      . "$(rustc --print sysroot)/etc/bash_completion.d/cargo"
      source <(rustup completions bash)

- name: "install CLion"
  become: yes
  community.general.snap:
    name: clion
    classic: yes
