---
- name: "Manage workstation"
  hosts: "localhost"
  connection: "local"

  vars:
    go_version: "1.17.8"

  tasks:
    - name: "Apt update & upgrade"
      become: true
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: "Base packages"
      become: true
      ansible.builtin.package:
        name:
          - build-essential
          - curl
          - docker.io
          - docker-compose
          - firefox
          - fzf
          - gcc
          - git
          - lynx
          - m4
          - make
          - pandoc
          - shellcheck
          - sqlite3
          - tig
          - vim-gtk3
        state: latest

    - name: "Ensure Bitwarden CLI installed"
      become: true
      community.general.snap:
        name: bw

    - ansible.builtin.include_tasks:
        file: "{{ include_path }}"
        apply:
          tags: "{{ include_path | basename | splitext | first }}"
      tags: always
      loop: "{{ query('fileglob', '*.yml') | reject('search', 'workstation.yml') }}"
      loop_control:
        loop_var: include_path
        
