---
- hosts: "localhost"
  roles:
    - role: ubuntu
      tags: ubuntu
    - role: dev
      tags: dev
    - role: k8s
      tags: k8s
    - role: aws
      tags: aws
    - role: java
      tags: java
    - role: go
      tags: go
      vars:
        go_version: "1.17.8"
    - role: node
      tags: node
    - role: rust
      tags: rust
