- name: "install sdkman"
  ansible.builtin.shell:
    cmd: mv ~/.bashrc ~/.bashrc.bak && curl -s "https://get.sdkman.io" | SDKMAN_DIR={{ xdg_data_home }}/sdkman bash
    creates: "{{ xdg_data_home }}/sdkman"
  notify: sdkman installed

- name: "install IDEA"
  become: true
  community.general.snap:
    name: intellij-idea-ultimate
    classic: true
