- name: "ensure sdkman installed"
  ansible.builtin.shell:
    cmd: curl -s "https://get.sdkman.io" | SDKMAN_DIR={{ xdg_data_home }}/sdkman bash
    creates: "{{ xdg_data_home }}/sdkman"

- name: "bashrc sdkman"
  ansible.builtin.copy:
    dest: "{{ xdg_config_home }}/bash/100.sdkman.sh"
    content: |
     export SDKMAN_DIR="${XDG_DATA_HOME:-"$HOME/.local/share"}/sdkman"
     [[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

- name: "install IDEA"
  become: true
  community.general.snap:
    name: intellij-idea-ultimate
    classic: true
