- name: "create sdkman bashrc"
  ansible.builtin.copy:
    dest: "{{ xdg_config_home }}/bash/100.sdkman.sh"
    content: ""
    force: false

- name: "install sdkman"
  ansible.builtin.shell:
    cmd: |
      unshare -Urm <<EOF
        mount --bind "{{ xdg_config_home }}/bash/100.sdkman.sh" "{{ ansible_user_dir }}/.bashrc"
        curl -s "https://get.sdkman.io" | SDKMAN_DIR="{{ xdg_data_home }}/sdkman" bash
      EOF
      rm -f "{{ ansible_user_dir }}/.zshrc"
    creates: "{{ xdg_data_home }}/sdkman"

- name: "java bashrc"
  ansible.builtin.copy:
    dest: "{{ xdg_config_home }}/bash/100.java.sh"
    content: |
      export JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

- name: "install IDEA"
  become: true
  community.general.snap:
    name: intellij-idea-ultimate
    classic: true
