- name: "create sdkman bashrc"
  ansible.builtin.copy:
    dest: "{{ xdg_config_home }}/bash/100.sdkman.sh"
    content: ""
    force: false

- name: "install sdkman"
  ansible.builtin.shell:
    cmd: unshare -Urm sh -c 'mount --bind {{ xdg_config_home }}/bash/100.sdkman.sh {{ ansible_user_dir }}/.bashrc && curl -s "https://get.sdkman.io" | SDKMAN_DIR={{ xdg_data_home }}/sdkman bash'
    creates: "{{ xdg_data_home }}/sdkman"

- name: "install IDEA"
  become: true
  community.general.snap:
    name: intellij-idea-ultimate
    classic: true
