- name: "ensure sdkman installed"
  ansible.builtin.shell:
    cmd: curl -s "https://get.sdkman.io" | SDKMAN_DIR={{ ansible_user_dir }}/.local/share/sdkman bash
    creates: "{{ ansible_user_dir }}/.local/share/sdkman"

- name: "bashrc sdkman"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/bash/100.sdkman.sh"
    content: |
     export SDKMAN_DIR="$XDG_DATA_HOME/sdkman"
     [[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

- name: "install IDEA"
  become: yes
  community.general.snap:
    name: intellij-idea-ultimate
    classic: yes
