- name: "configure dock"
  ansible.builtin.command:
    cmd: dconf load /org/gnome/shell/extensions/dash-to-dock/
    stdin: |
        [/]
        dock-fixed=false
        dock-position='BOTTOM'
        extend-height=false
        intellihide=false
        multi-monitor=true
        preferred-monitor=0
