- name: "install Jetbrains Mono"
  ansible.builtin.unarchive:
    src: https://download.jetbrains.com/fonts/JetBrainsMono-2.242.zip
    remote_src: true
    dest: "{{ xdg_data_home }}/"
    include: fonts/*
    creates: "{{ xdg_data_home }}/fonts/ttf/JetBrainsMono-Regular.ttf"
  register: jetbrains_mono

- name: "reload font cache"
  ansible.builtin.command: fc-cache -f -v
  when: jetbrains_mono.changed
