- name: "check for kitty install"
  ansible.builtin.command: kitty --version
  ignore_errors: true
  register: find_kitty
  changed_when: false

- name: "ensure kitty installed"
  ansible.builtin.shell:
    cmd: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n
    creates: "{{ ansible_user_dir }}/.local/kitty.app/bin/kitty"
  when: find_kitty.failed

- name: "kitty executable symlink"
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.local/kitty.app/bin/kitty"
    path: "{{ ansible_user_dir }}/.local/bin/kitty"
    state: link

- name: "kitty desktop files"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ xdg_data_home }}/applications/"
    force: false
  with_fileglob: "{{ ansible_user_dir }}/.local/kitty.app/share/applications/kitty*.desktop"

- name: "kitty desktop icon"
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regex: "Icon=Kitty"
    line: "Icon={{ ansible_user_dir }}/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png"
  with_fileglob: "{{ xdg_data_home }}/applications/kitty*.desktop"

- name: "kitty config dirs"
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/kitty"
    state: directory

- name: "kitty config file"
  ansible.builtin.copy:
    force: false
    dest: "{{ xdg_config_home }}/kitty/kitty.conf"
    content: |
      font_family          Jetbrains Mono
      font_size            11.0
      enable_audio_bell    false
      tab_bar_edge         top
      tab_bar_style        powerline
      shell_integration    disabled
      allow_remote_control true
      linux_display_server x11

      # BEGIN_KITTY_THEME
      # Space Gray Eighties
      include current-theme.conf
      # END_KITTY_THEME

- name: "fetch kitty theme"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/dexpota/kitty-themes/master/themes/SpaceGray_Eighties.conf
    dest: "{{ xdg_config_home }}/kitty/current-theme.conf"

- name: "bashrc kitty"
  ansible.builtin.copy:
    dest: "{{ xdg_config_home }}/bash/100.kitty.sh"
    content: |
      source <(kitty + complete setup bash)
