- name: "check for zoom install"
  ansible.builtin.command: which zoom
  changed_when: no
  ignore_errors: yes
  register: find_zoom

- name: "install zoom"
  become: true
  ansible.builtin.apt:
    deb: https://zoom.us/client/latest/zoom_amd64.deb
  when: find_zoom.failed

