
- name: "download go {{ go_version }}"
  ansible.builtin.unarchive:
    src: https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz
    remote_src: yes
    dest: "{{ ansible_user_dir }}/.local/"
    creates: "{{ ansible_user_dir }}/.local/go{{ go_version }}"
    extra_opts:
      - "--transform"
      - "s/^go/go{{ go_version }}/"

- name: "bashrc go"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.bashrc.d/100.go.sh"
    content: |
      path_prepend PATH "$HOME/.local/go{{ go_version }}/bin"
      path_prepend PATH "$HOME/go/bin"

- name: "vim-go plugin"
  ansible.builtin.git:
    depth: 1
    repo: "https://github.com/fatih/vim-go"
    update: no
    version: "v1.26"
    dest: "{{ ansible_user_dir }}/.config/vim/pack/plugins/start/vim-go"

- name: "go.vim ftplugin"
  ansible.builtin.copy:
    src: ftplugin/go.vim
    remote_src: false
    dest: "{{ ansible_user_dir }}/.config/vim/ftplugin/"
