- name: "download go {{ go_version }}"
  ansible.builtin.unarchive:
    src: https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz
    remote_src: true
    dest: "{{ xdg_data_home }}/"
    creates: "{{ xdg_data_home }}/go{{ go_version }}"
    extra_opts:
      - "--transform"
      - "s/^go/go{{ go_version }}/"

- name: "bashrc go"
  ansible.builtin.copy:
    dest: "{{ xdg_config_home }}/bash/100.go.sh"
    content: |
      export GOPATH="${XDG_DATA_HOME:-"$HOME/.local/share"}/go"
      path_prepend PATH "${XDG_DATA_HOME:-"$HOME/.local/share"}/go{{ go_version }}/bin"
      path_prepend PATH "$GOPATH/bin"

- name: "vim-go plugin"
  ansible.builtin.git:
    depth: 1
    repo: "https://github.com/fatih/vim-go"
    update: false
    version: "v1.26"
    dest: "{{ xdg_config_home }}/vim/pack/plugins/start/vim-go"

- name: "go.vim ftplugin"
  ansible.builtin.copy:
    src: ftplugin/go.vim
    remote_src: false
    dest: "{{ xdg_config_home }}/vim/ftplugin/"
