- name: "nvm bashrc"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/bash/100.nvm.sh"
    content: ''
    force: no

- name: "ensure nvm installed"
  ansible.builtin.shell:
    cmd: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | NVM_DIR={{ ansible_user_dir }}/.config/nvm PROFILE={{ ansible_user_dir }}/.config/bash/100.nvm.sh bash"
    creates: "{{ ansible_user_dir }}/.config/nvm"

- name: "node bashrc"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/bash/100.node.sh"
    content: |
      export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history

