- name: "nvm bashrc"
  ansible.builtin.copy:
    dest: "{{ xdg_config_home }}/bash/100.nvm.sh"
    content: ''
    force: false

- name: "XDG_DATA_HOME/nvm dir"
  ansible.builtin.file:
    path: "{{ xdg_data_home }}/nvm"
    state: directory
  register: mkdir_nvm

- name: "install nvm v{{ nvm_version }}"
  ansible.builtin.shell:
    cmd: "curl -s -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash"
  when: mkdir_nvm.changed
  environment:
    NVM_DIR: "{{ xdg_data_home }}/nvm"
    PROFILE: "{{ xdg_config_home }}/bash/100.nvm.sh"

- name: "nvm bash completion"
  ansible.builtin.lineinfile:
    line: '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
    path: "{{ xdg_config_home }}/bash/100.nvm.sh"

- name: "node bashrc"
  ansible.builtin.copy:
    dest: "{{ xdg_config_home }}/bash/100.node.sh"
    content: |
      export NODE_REPL_HISTORY="${XDG_DATA_HOME:-"$HOME/.local/share"}/node_repl_history"
      export NPM_PREFIX="${XDG_DATA_HOME:-"$HOME/.local/share"}/npm"
      export NPM_CACHE="${XDG_CACHE_HOME:-"$HOME/.cache"}/npm"
      export NPM_TMP="${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp/user/$UID}}/npm"

- name: "Create NPM_PREFIX dir"
  ansible.builtin.file:
    path: "{{ xdg_data_home }}/npm"
    state: directory
