- name: "docker packages"
  become: true
  ansible.builtin.package:
    name:
      - docker.io
      - docker-compose

- name: "add {{ ansible_user_id }} to docker group"
  become: true
  ansible.builtin.user: 
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
