- name: "Git packages"
  become: true
  ansible.builtin.package:
    name:
      - git
      - tig

- name: "git config dir"
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/git/"
    state: directory

- name: "user git config"
  ansible.builtin.copy:
    dest: "{{ xdg_config_home }}/git/config"
    content: |
      [user]
          name = Matt McShane
          email = matt@mattmcshane.com
      [fetch]
          prune = true
      [commit]
          verbose = true
      [includeIf "gitdir:~/temporalio/"]
          path = ~/temporalio/.gitconfig

- name: "XDG_DATA_HOME/tig"
  ansible.builtin.file:
    path: "{{ xdg_data_home }}/tig"
    state: directory
