- name: "Git packages"
  become: true
  ansible.builtin.package:
    name:
      - git
      - tig

- name: "git config dir"
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/git/"
    state: directory

- name: "user git config"
  ansible.builtin.copy:
    dest: "{{ xdg_config_home }}/git/config"
    content: |
      [user]
          name = Matt McShane
          email = matt@mattmcshane.com
      [fetch]
          prune = true
      [commit]
          verbose = true
      [alias]
          amend = commit --amend --no-edit
          lf = log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%an]" --decorate --numstat
      [includeIf "gitdir:~/temporalio/"]
          path = ~/temporalio/.gitconfig
      [blame]
          ignoreRevsFile = .git-blame-ignore-revs

- name: "XDG_DATA_HOME/tig"
  ansible.builtin.file:
    path: "{{ xdg_data_home }}/tig"
    state: directory
