- name: "Git packages"
  become: true
  ansible.builtin.package:
    name:
      - git
      - tig

- name: "git config dir"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/git/"
    state: directory

- name: "user git config"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/git/config"
    content: |
      [user]
          name = Matt McShane
          email = matt@mattmcshane.com
      [fetch]
          prune = true
      [commit]
          verbose = true
      [includeIf "gitdir:~/temporalio/"]
          path = ~/temporalio/.gitconfig

