- name: "clone rbenv"
  ansible.builtin.git:
    depth: 1
    single_branch: true
    dest: "{{ rbenv_install_home }}"
    repo: 'https://github.com/rbenv/rbenv'

- name: "set up rbenv shared data dirs"
  ansible.builtin.file:
    path: "{{ path }}"
    state: directory
  loop:
    - "{{ rbenv_root }}/plugins"
    - "{{ rbenv_root }}/shims"
    - "{{ rbenv_root }}/versions"
  loop_control:
    loop_var: path

- name: "clone ruby-build"
  ansible.builtin.git:
    depth: 1
    single_branch: true
    dest: "{{ rbenv_root }}/plugins/ruby-build"
    repo: 'https://github.com/rbenv/ruby-build'

- name: "rbenv bash configuration"
  ansible.builtin.copy:
    dest: "{{ xdg_config_home }}/bash/100.rbenv.sh"
    content: |
      export RBENV_ROOT="{{ rbenv_root }}"
      eval "$({{ rbenv_install_home }}/bin/rbenv init - bash)"

